---
- include: preflight.yml
  tags:
    - gobetween_install
    - gobetween_configure
    - gobetween_health
    - gobetween_run

- include: install_app.yml
  become: true
  tags:
    - gobetween_install

- include: configure.yml
  become: true
  tags:
    - gobetween_configure

- include: healthcheck.yml
  become: true
  tags:
    - gobetween_health

- name: "Ensure gobetween service is started and enabled"
  become: true
  service:
    daemon_reload: true
    name: gobetween
    state: started
    enabled: true
    masked: false
  tags:
    - gobetween_run

- name: flush handlers
  meta: flush_handlers
