---
- name: "Create {{ gobetween_owner_group }} system group"
  group:
    name: "{{ gobetween_owner_group }}"
    system: true
    state: present

- name: "Create {{ gobetween_owner }} system user"
  user:
    name: "{{ gobetween_owner }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ gobetween_owner_group }}"
    createhome: false

- name: "Create an install dir {{ gobetween_install_dir }}"
  file:
    path: "{{ gobetween_install_dir }}"
    state: directory
    owner: "{{ gobetween_owner_group }}"
    group: "{{ gobetween_owner_group }}"
    mode: 0755

- name: "Create log file"
  file:
    path: "{{ gobetween_log_file }}"
    state: touch
    owner: "{{ gobetween_owner_group }}"
    group: "{{ gobetween_owner_group }}"
    mode: 0644
  changed_when: false

- when: not gobetween_binary.stat.exists or ( gobetween_ins_version is defined and gobetween_ins_version.stdout != "0.8.0+snapshot")
  block:
    - name: "Download gobetween..."
      get_url:
        url: "{{ gobetween_tgz_url }}"
        dest: "/tmp/{{ gobetween_tgz }}"
        timeout: 120
        mode: 0644
      when: not gobetween_install_local

    - name: "Unarchive gobetween..."
      unarchive:
        remote_src: true
        src: "/tmp/{{ gobetween_tgz }}"
        dest: "/tmp/"
        mode: 0644
      when: not gobetween_install_local

    - name: "Copy gobetween binary..."
      copy:
        src: "/tmp/gobetween"
        dest: "{{ gobetween_binary_file }}"
        mode: 0755
        remote_src: true
      when: not gobetween_install_local

    - name: "Copy gobetween local binary..."
      copy:
        src: '{{ gobetween_local_file }}'
        dest: '{{ gobetween_binary_file }}'
        mode: '0755'
      when: gobetween_install_local
